/* Generated by Yosys 0.33+72 (git sha1 ac8b31e00, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "tt_um_reaction_timer.v:1.1-29.10" *)
module tt_um_reaction_timer(clk, rst_n, ui_in, uo_out, uio_out, uio_oe, ena);
  (* src = "tt_um_reaction_timer.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "tt_um_reaction_timer.v:8.16-8.19" *)
  input ena;
  wire ena;
  (* src = "tt_um_reaction_timer.v:3.16-3.21" *)
  input rst_n;
  wire rst_n;
  (* src = "tt_um_reaction_timer.v:4.22-4.27" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "tt_um_reaction_timer.v:7.23-7.29" *)
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  (* src = "tt_um_reaction_timer.v:6.23-6.30" *)
  output [7:0] uio_out;
  wire [7:0] uio_out;
  (* src = "tt_um_reaction_timer.v:5.23-5.29" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  assign uio_oe = 8'hxx;
  assign uio_out = 8'hxx;
  assign uo_out = 8'hxx;
endmodule
